import type { ActivoValorado, AnalisRiesgo, Escala } from "@/types/riesgos";

// Activos con valoración y criticidad
export const activosValorados: ActivoValorado[] = [
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-001",
    nombre: "EQUIPO DE CÓMPUTO",
    areaGeografica: 1,
    periodoAfectacion: 2,
    impacto: 2,
    cantidadIcAfectadas: 2,
    camposAfectados: 2,
    interdependencia: 3,
    criticidad: "III",
    infraestructurasCriticas: "No aplica",
    gradoCriticidad: "—",
    controlesImplementar: "—",
  },
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-002",
    nombre: "KIT DE HERRAMIENTAS Y CONSUMIBLES",
    areaGeografica: 1,
    periodoAfectacion: 1,
    impacto: 1,
    cantidadIcAfectadas: 1,
    camposAfectados: 1,
    interdependencia: 1,
    criticidad: "I",
    infraestructurasCriticas: "No aplica",
    gradoCriticidad: "—",
    controlesImplementar: "—",
  },
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-003",
    nombre: "REPORTE TÉCNICO DE INTERVENCIÓN",
    areaGeografica: 2,
    periodoAfectacion: 2,
    impacto: 3,
    cantidadIcAfectadas: 2,
    camposAfectados: 2,
    interdependencia: 3,
    criticidad: "IV",
    infraestructurasCriticas: "REPORTE TÉCNICO DE INTERVENCIÓN",
    gradoCriticidad: "IV",
    controlesImplementar: "Digitalizar reportes en ITSM con firma electrónica, respaldo automático en la nube",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-004",
    nombre: "PLATAFORMA ITSM",
    areaGeografica: 3,
    periodoAfectacion: 3,
    impacto: 5,
    cantidadIcAfectadas: 3,
    camposAfectados: 3,
    interdependencia: 5,
    criticidad: "V",
    infraestructurasCriticas: "PLATAFORMA ITSM",
    gradoCriticidad: "V",
    controlesImplementar: "Plan de continuidad manual, SLA con penalidades al proveedor, monitoreo de uptime 24/7",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-005",
    nombre: "HISTORIAL DE TICKETS E INCIDENCIAS",
    areaGeografica: 3,
    periodoAfectacion: 2,
    impacto: 4,
    cantidadIcAfectadas: 2,
    camposAfectados: 3,
    interdependencia: 4,
    criticidad: "V",
    infraestructurasCriticas: "HISTORIAL DE TICKETS E INCIDENCIAS",
    gradoCriticidad: "V",
    controlesImplementar: "Implementar RBAC, auditorías de acceso mensuales, cifrado en reposo y en tránsito",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-006",
    nombre: "CANAL DE COMUNICACIÓN CON EL CLIENTE",
    areaGeografica: 2,
    periodoAfectacion: 1,
    impacto: 2,
    cantidadIcAfectadas: 1,
    camposAfectados: 2,
    interdependencia: 2,
    criticidad: "III",
    infraestructurasCriticas: "No aplica",
    gradoCriticidad: "—",
    controlesImplementar: "—",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-007",
    nombre: "BASE DE DATOS DE INVENTARIO TECNOLÓGICO",
    areaGeografica: 3,
    periodoAfectacion: 3,
    impacto: 5,
    cantidadIcAfectadas: 3,
    camposAfectados: 3,
    interdependencia: 5,
    criticidad: "V",
    infraestructurasCriticas: "BASE DE DATOS DE INVENTARIO TECNOLÓGICO",
    gradoCriticidad: "V",
    controlesImplementar: "Backups automáticos diarios cifrados, pruebas de restauración trimestrales, MFA en acceso a base de datos",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-008",
    nombre: "REPORTE PERIÓDICO DE ESTADO DEL PARQUE TI",
    areaGeografica: 1,
    periodoAfectacion: 2,
    impacto: 2,
    cantidadIcAfectadas: 1,
    camposAfectados: 2,
    interdependencia: 2,
    criticidad: "III",
    infraestructurasCriticas: "No aplica",
    gradoCriticidad: "—",
    controlesImplementar: "—",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-009",
    nombre: "PLAN DE RENOVACIÓN TECNOLÓGICA",
    areaGeografica: 2,
    periodoAfectacion: 1,
    impacto: 2,
    cantidadIcAfectadas: 1,
    camposAfectados: 1,
    interdependencia: 1,
    criticidad: "II",
    infraestructurasCriticas: "No aplica",
    gradoCriticidad: "—",
    controlesImplementar: "—",
  },
];

// Escalas de referencia
export const escalas: Escala[] = [
  {
    nombre: "Severidad",
    valores: [
      { valor: 1, descripcion: "Poca o nula severidad en el grado de vulnerabilidad" },
      { valor: 2, descripcion: "Severidad moderada por el grado de vulnerabilidad" },
      { valor: 3, descripcion: "Altamente severo el nivel de vulnerabilidad" },
    ],
  },
  {
    nombre: "Exposición",
    valores: [
      { valor: 1, descripcion: "Poca o nula exposición" },
      { valor: 2, descripcion: "Nivel moderado de exposición" },
      { valor: 3, descripcion: "Altamente expuesto" },
    ],
  },
  {
    nombre: "Capacidad",
    valores: [
      { valor: 1, descripcion: "Poca o nula capacidad de realizar el ataque" },
      { valor: 2, descripcion: "Capacidad moderada. Se tiene el conocimiento y habilidades para realizar el ataque, pero pocos recursos" },
      { valor: 3, descripcion: "Altamente capaz. Se tienen los conocimientos, habilidades y recursos necesarios para realizar un ataque" },
    ],
  },
  {
    nombre: "Motivación",
    valores: [
      { valor: 1, descripcion: "Poca o nula motivación. No se está inclinado a actuar" },
      { valor: 2, descripcion: "Nivel moderado de motivación. Se actuará si se le pide o provoca" },
      { valor: 3, descripcion: "Altamente motivado. Casi seguro que intentará el ataque" },
    ],
  },
];

// Análisis completo con vulnerabilidades y amenazas
export const analisRiesgos: AnalisRiesgo[] = [
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-001",
    nombre: "EQUIPO DE CÓMPUTO",
    confidencialidad: 3,
    integridad: 3,
    disponibilidad: 5,
    totalValor: 11,
    valor1: "Alto",
    valor2: 3,
    vulnerabilidades: "Ausencia de programa de mantenimiento preventivo documentado",
    amenazas: "Fallo mecánico / eléctrico por desgaste acumulado",
    eventoAmenaza: "Interrupción del servicio por daño irreparable al equipo del cliente",
    controles: "Establecer calendario de mantenimiento preventivo firmado por el cliente, registrar cada intervención en ITSM con checklist validado",
  },
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-002",
    nombre: "KIT DE HERRAMIENTAS Y CONSUMIBLES",
    confidencialidad: 1,
    integridad: 3,
    disponibilidad: 4,
    totalValor: 8,
    valor1: "Medio",
    valor2: 2,
    vulnerabilidades: "Falta de control de existencias y reposición reactiva de consumibles",
    amenazas: "Indisponibilidad de la herramienta crítica durante visita táctica",
    eventoAmenaza: "Visita de mantenimiento incompleta por carencia de relaciones o herramientas",
    controles: "Implementar inventario mínimo de consumibles con puntos de reorden, verificar kit antes de cada visita",
  },
  {
    idProceso: "SNB_MAN_01",
    idActivo: "A-003",
    nombre: "REPORTE TÉCNICO DE INTERVENCIÓN",
    confidencialidad: 3,
    integridad: 5,
    disponibilidad: 3,
    totalValor: 11,
    valor1: "Alto",
    valor2: 3,
    vulnerabilidades: "Registro manual sin validación de integridad ni control de versiones",
    amenazas: "Alteración o pérdida del reporte antes de la firma del cliente",
    eventoAmenaza: "Disputa legal o incumplimiento de SLA por reporte incompleto o no firmado",
    controles: "Digitalizar reportes en ITSM con firma electrónica del cliente; respaldo automáticamente en la nube al cierre del ticket",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-004",
    nombre: "PLATAFORMA ITSM",
    confidencialidad: 2,
    integridad: 5,
    disponibilidad: 5,
    totalValor: 12,
    valor1: "Alto",
    valor2: 3,
    vulnerabilidades: "Dependencia de un único proveedor SaaS sin plan de continuidad documentado",
    amenazas: "Interrupción no planificada del servicio en la nube (caída del proveedor)",
    eventoAmenaza: "Incumplimiento masivo de SLAs por indisponibilidad total de la plataforma ITSM",
    controles: "Definir plan de continuidad con procedimiento manual de tickets, exigir SLA al proveedor con penalidades, monitoreo de uptime con alertas automáticas",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-005",
    nombre: "HISTORIAL DE TICKETS E INCIDENCIAS",
    confidencialidad: 4,
    integridad: 5,
    disponibilidad: 4,
    totalValor: 13,
    valor1: "Alto",
    valor2: 3,
    vulnerabilidades: "Ausencia de controles de acceso granulares por rol de usuario",
    amenazas: "Acceso no autorizado al historial de incidencias de clientes",
    eventoAmenaza: "Fuga de información confidencial del cliente y posible violación a normativas de privacidad",
    controles: "Implementar RBAC (control de acceso basado en roles), auditorías de acceso mensuales, cifrado de datos en reposo y en tránsito",
  },
  {
    idProceso: "SNB_SOP_02",
    idActivo: "A-006",
    nombre: "CANAL DE COMUNICACIÓN CON EL CLIENTE",
    confidencialidad: 2,
    integridad: 3,
    disponibilidad: 4,
    totalValor: 9,
    valor1: "Medio",
    valor2: 2,
    vulnerabilidades: "Falta de canal alternativo documentado ante falla del modo principal",
    amenazas: "Indisponibilidad del canal oficial de reporte de incidentes, agravando el impacto operativo",
    eventoAmenaza: "Usuario incapaz de reportar incidentes urgentes, agravando el impacto operativo",
    controles: "Definir al menos dos canales de comunicación alternativos documentados, notificar a clientes en caso de falla del canal principal",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-007",
    nombre: "BASE DE DATOS DE INVENTARIO TECNOLÓGICO",
    confidencialidad: 5,
    integridad: 5,
    disponibilidad: 4,
    totalValor: 14,
    valor1: "Alto",
    valor2: 3,
    vulnerabilidades: "Sin política de respaldo periódico ni procedimiento de recuperación ante desastres",
    amenazas: "Ransomware o corrupción de datos que afecta la base de datos del cliente con impacto en su vida de activos",
    eventoAmenaza: "Pérdida total o parcial de la base de datos del inventario del cliente con impacto en su decisión de ciclo de vida de activos",
    controles: "Establecer backups automáticos diarios cifrados con retención de 30 días, realizar pruebas de restauración trimestrales, activar MFA en acceso a base de datos",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-008",
    nombre: "REPORTE PERIÓDICO DE ESTADO DEL PARQUE TI",
    confidencialidad: 2,
    integridad: 3,
    disponibilidad: 3,
    totalValor: 8,
    valor1: "Medio",
    valor2: 2,
    vulnerabilidades: "Proceso de generación de reportes no automatizado y dependiente de criterio técnico individual",
    amenazas: "Error humano en la consolidación de datos del parque tecnológico",
    eventoAmenaza: "Reporte con datos incorrectos que lleva a decisiones erróneas sobre el parque tecnológico del cliente",
    controles: "Automatizar generación de reportes desde ITSM con plantilla estandarizada, establecer revisión por segunda persona antes de entregar al cliente",
  },
  {
    idProceso: "SNB_INV_03",
    idActivo: "A-009",
    nombre: "PLAN DE RENOVACIÓN TECNOLÓGICA",
    confidencialidad: 3,
    integridad: 4,
    disponibilidad: 2,
    totalValor: 9,
    valor1: "Medio",
    valor2: 2,
    vulnerabilidades: "Criterios de obsolescencia no definidos formalmente ni documentados",
    amenazas: "Planificación de renovación basada en percepción subjetiva sin métricas objetivas",
    eventoAmenaza: "Plan de renovación ineficiente que genera sobrecostos o riesgos operativos no mitigados para el cliente",
    controles: "Definir política de ciclo de vida de activos con criterios técnicos documentados (antigüedad, fallas recurrentes, soporte del fabricante), validar plan con dirección",
  },
];
import type { Riesgo, Clasificacion, NivelRiesgo } from "@/types/riesgos";

function probabilidadDesdeValor2(valor2: number): Clasificacion {
  if (valor2 <= 1) return "Baja";
  if (valor2 === 2) return "Media";
  return "Alta";
}

function impactoDesdeCia(confidencialidad: number, integridad: number, disponibilidad: number): Clasificacion {
  const sumaCia = confidencialidad + integridad + disponibilidad;
  if (sumaCia <= 7) return "Baja";
  if (sumaCia <= 11) return "Media";
  return "Alta";
}

function nivelGlobalDesdeValor1(valor1: string, totalValor: number): NivelRiesgo {
  if (totalValor >= 13) return "Crítico";
  if (valor1 === "Alto") return "Alto";
  if (valor1 === "Medio") return "Medio";
  return "Bajo";
}

function procesoCorto(idProceso: string): string {
  // "SNB_MAN_01" -> "MAN_01"
  return idProceso.replace(/^SNB_/, "");
}

export const riesgos: Riesgo[] = analisRiesgos.map((r) => ({
  id: r.idActivo,
  proceso: procesoCorto(r.idProceso),
  descripcion: r.amenazas,
  causa: r.vulnerabilidades,
  probabilidad: probabilidadDesdeValor2(r.valor2),
  impacto: impactoDesdeCia(r.confidencialidad, r.integridad, r.disponibilidad),
  nivelGlobal: nivelGlobalDesdeValor1(r.valor1, r.totalValor),
  mitigacion: r.controles,
}));